import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

import { FooterSitemapLinks } from 'components/Footer';
import { Navbar } from 'components/Navbar';

import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Classified Ads',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar />
        {children}
        <FooterSitemapLinks />
      </body>
    </html>
  );
};

export default RootLayout;
